//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ОТК_ЗАО__Русская_косметика_
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyClients
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CompanyClients()
        {
            this.Orders = new HashSet<Orders>();
        }
    
        public string CompanyID { get; set; }
        public string CompanyName { get; set; }
        public string Address { get; set; }
        public string INN { get; set; }
        public string R_S { get; set; }
        public string BIK { get; set; }
        public string DirectorFIO { get; set; }
        public string ContactFIO { get; set; }
        public string ContactPhone { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
    }
}
