//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ОТК_ЗАО__Русская_косметика_
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        private static Entities _instance;
        public Entities()
            : base("name=Entities")
        {
        }

        public static Entities GetContext()
        {
            if (_instance == null) 
                _instance = new Entities();
            return _instance;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CompanyClients> CompanyClients { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<PersonClients> PersonClients { get; set; }
        public virtual DbSet<ServiceInOrder> ServiceInOrder { get; set; }
        public virtual DbSet<Services> Services { get; set; }
        public virtual DbSet<Statuses> Statuses { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<WorkerPosts> WorkerPosts { get; set; }
        public virtual DbSet<Workers> Workers { get; set; }
    }
}
