//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ОТК_ЗАО__Русская_косметика_
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orders()
        {
            this.ServiceInOrder = new HashSet<ServiceInOrder>();
        }
    
        public int OrderID { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<int> PersonFK { get; set; }
        public string CompanyFK { get; set; }
        public Nullable<int> StatusFK { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public Nullable<int> WorkerFK { get; set; }
        public Nullable<int> PeriodExecution { get; set; }
    
        public virtual CompanyClients CompanyClients { get; set; }
        public virtual PersonClients PersonClients { get; set; }
        public virtual Statuses Statuses { get; set; }
        public virtual Workers Workers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceInOrder> ServiceInOrder { get; set; }
    }
}
